"""Update payment method

Revision ID: 29244a3a01af
Revises: 70f51caa944e
Create Date: 2024-08-19 17:41:24.589074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29244a3a01af'
down_revision = '70f51caa944e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(length=255), nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
