"""more model and route changes

Revision ID: 6661d3cb9017
Revises: e5828afbda0c
Create Date: 2024-08-14 09:28:32.701070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6661d3cb9017'
down_revision = 'e5828afbda0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        # Add the foreign key constraint with a name
        batch_op.create_foreign_key(
            'fk_donation_event',  # Constraint name
            'event',              # Referenced table
            ['event_id'],         # Local column
            ['id']                # Referenced column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        # Drop the foreign key constraint by name
        batch_op.drop_constraint('fk_donation_event', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
