"""Updated relationships

Revision ID: 70f51caa944e
Revises: 903b6c8c4fb7
Create Date: 2024-08-19 15:26:22.806831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f51caa944e'
down_revision = '903b6c8c4fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isActive')

    # ### end Alembic commands ###
