"""update donation model

Revision ID: 7218f416a4b3
Revises: 9b533db272c8
Create Date: 2024-08-15 21:29:55.108374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7218f416a4b3'
down_revision = '9b533db272c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('fk_donation_event', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_donation_event', 'event', ['event_id'], ['id'])
        batch_op.drop_column('message')

    # ### end Alembic commands ###
