"""Updated relationships

Revision ID: 903b6c8c4fb7
Revises: b7f1dc4c505c
Create Date: 2024-08-19 14:37:55.202294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903b6c8c4fb7'
down_revision = 'b7f1dc4c505c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
