"""admin model and routes

Revision ID: 92293189c7d4
Revises: 9c5e0074d586
Create Date: 2024-08-13 20:12:56.767292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92293189c7d4'
down_revision = '9c5e0074d586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
