from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b533db272c8'
down_revision = 'd6a7e9726d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_donation_event', 'event', ['event_id'], ['id'])
        # Provide a name for the foreign key constraint (e.g., 'fk_donation_event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_event', type_='foreignkey')
        # Use the same name as in the upgrade() function
        batch_op.drop_column('timestamp')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
