"""model and route changes

Revision ID: d6a7e9726d1d
Revises: 6661d3cb9017
Create Date: 2024-08-14 09:38:49.422176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a7e9726d1d'
down_revision = '6661d3cb9017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_event', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key('fk_donation_event', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
